name: deploy-rc-on-stag

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dockerize:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_GITHUB_CHANNEL_WEBHOOK }}
          title: "Deploy design-system release candidate on stag: Starting"
          description: ""
          color: 0xffed2b
          username: GitHub Actions

      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Ensure main branch is not ahead
        run: bash .scripts/main-not-ahead-of.sh --branch ${GITHUB_REF#refs/heads/}
      
      - name: Git Identity
        run: |
          git config --global user.name 'geovbot'
          git config --global user.email 'github.bot@geovistory.org'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install Lerna globally
        run: npm install lerna --location=global
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Clean install dependencies
        run: npm ci

      - name: Build
        run: npm run build
      
      - uses: EndBug/add-and-commit@v5
        with:
          message: 'chore(): update build artifacts'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Tag this commit with issue-tag 
        id: lerna
        run: |
          lerna version prepatch --preid staging --yes
          echo ::set-output name=tag::$(cd ./packages/design-system-web && cat package.json | jq -r '.version')
        env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Echo tag created by lerna
        run: echo your branch is '${{steps.lerna.outputs.tag}}'
     
      - name: Update Lock files
        run: 'npm run update:lock'

      - uses: EndBug/add-and-commit@v5
        with:
          message: 'chore(): update lock files'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/geovistory/design-system:${{steps.lerna.outputs.tag}}
      
      
      - name: Invoke workflow in public-chart to make a staging release
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update-docker-image-tag
          repo: geovistory/public-chart
          ref: stag
          token: ${{ secrets.GEOVBOT_PAT_REPO }}
          inputs: |
            {
              "service": "design-system",
              "tag": "${{steps.lerna.outputs.tag}}",
              "environment": "stag"
            }
            
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_GITHUB_CHANNEL_WEBHOOK }}
          title: "Deploy design-system release candidate on stag: Done"
          description: ""
          color: 0x0000ff
          username: GitHub Actions
